# coding:utf-8

time_out: 200                   # timeout for crawling and storing user info
min_crawl_interal: 5           # min interal of http request
max_crawl_interal: 10           # max interal of http request
excp_interal: 5*60              # time for sleeping when crawling raises exceptions

max_follow_page: 2 # 抓取粉丝、关注页的最大页码


db:
  host: 127.0.0.1
  port: 3306
  user: zhihu
  password: 123
  db_name: zhihu
  db_type: mysql

redis:
  host: 127.0.0.1
  port: 6379
  password: '123'
  broker: 6                    # broker for celery
  backend: 7                   # backed for celery